server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchange-service/**
          filters: []
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
          filters: []
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    urls:
      - name: book-service
        url: /book-service/v3/api-docs
      - name: exchange-service
        url: /exchange-service/v3/api-docs