server:
  port: 8765
spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: exchange-service
#          uri: lb://EXCHANGE-SERVICE
#          predicates:
#            - Path=/exchange-service/**
#          filters: []
#        - id: book-service
#          uri: lb://BOOK-SERVICE
#          predicates:
#            - Path=/book-service/**
#          filters: []
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka