server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  rateLimiter:
    instances:
      default:
        limit-for-period: 10
        limit-refresh-period: 5s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
      find-book:
        max-attempts: 10
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_microservice
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none