CREATE TABLE book (
  id BIGINT NOT NULL AUTO_INCREMENT,
  author VARCHAR(100) DEFAULT NULL,
  launch_date DATE DEFAULT NULL,
  price DECIMAL(11,2) DEFAULT NULL,
  title VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)