server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/msimeaor/matheus-config-server
          search-paths:
            - greeting-service
#  profiles:
#    active:
#      - native